prose:
  rooturl: 'contributions'
  siteurl: 'http://www.multibao.org'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "author"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "author"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Agile"
              value: "agile"
            - name: "Collaboratif"
              value: "collaboratif"
            - name: "Scopyleft"
              value: "scopyleft"
            - name: "Meteor"
              value: "meteor"
            - name: "Lean"
              value: "lean"
