daktary:
  home: /multibao/contributions/pages
  meta:
    title: 'multiBàO, une multi Boîte à Outils'
    description: 'multiBàO est une technologie collaborative, gratuite, libre, vous permettant de pleinement mutualiser votre documentation sur les approches participatives/gestion de projet avec les autres réseaux. '

  ghRepos:
    - label: Menu
      account: multibao
      repo: contributions
      folder: pages
      
    - label: Public
      account: multibao
      repo: contributions
      folder: contributions

    - label: Réseau transition
      account: reseautransitionwb
      repo: reseau_transition
      folder: contributions

    - label: Ingrédients Transition
      account: reseautransitionwb
      repo: reseau_transition
      folder: contributions/Ingrédients

    - label: Démocratie Ouverte
      account: alecoz
      repo: democratie_ouverte
      folder: contributions

    - label: Pratiques coopération
      account: multibao
      repo: contributions
      folder: contributions/cpcoop

    - label: Chiendent
      account: multibao
      repo: contributions
      folder: contributions/collectif_chiendent
  
    - label: Traducteurs agiles
      account: les-traducteurs-agiles
      repo: les-traducteurs-agiles.github.io
      folder: _posts

    - label: Holacraty
      account: holacracyone
      repo: Holacracy-Constitution
      folder: 

    - label: Systèmes locaux
      account: multibao
      repo: contributions/contributions
      folder: d_sidd

    - label: J.e.u.
      account: multibao
      repo: contributions
      folder: contributions/jeu

    - label: Orga personnelle
      account: wolffthomas
      repo: perles_gestion_projets
      folder: contributions

    - label: Travailler en Réseau
      account: lilianricaud
      repo: travail-en-reseau
      folder:
  
    - label: Construire Communs
      account: lilianricaud
      repo: Minga
      folder:

    - label: Coop-TIC
      account: supagroflorac
      repo: cooptic
      folder: contributions
  
    - label: TempsCommuns
      account: tempsdescommuns
      repo: contributions
      folder: 

    - label: Cre-sol
      account: RomainLalande
      repo: Cre-sol
      folder: 

    - label: EduTech
      account: multibao
      repo: contributions
      folder: contributions/edutech

    - label: Enseigner autrement
      account: onpassealacte
      repo: videos_initiatives
      folder: enseigner_autrement

    - label: Habiter ensemble
      account: onpassealacte
      repo: videos_initiatives
      folder: habiter_ensemble

    - label: Reinventer Démocratie
      account: onpassealacte
      repo: videos_initiatives
      folder: reinventer_democratie

    - label: Construire Réseaux
      account: onpassealacte
      repo: videos_initiatives
      folder: reinventer_collaboration_gouvernance

    - label: Co-Creative Recipes
      account: lilianricaud
      repo: co-creative-recipes
      folder:
      
  dkCss: assets/css/multibao.css
  dkImgPath: assets/img
  dk404: https://raw.githubusercontent.com/daktary/contribs/master/assets/img/error404.png

prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Auteurs"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Titre de la fiche"
          value: "Contribution multiBàO"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          help: "en une courte phrase"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Mots clés (max 5)"
          placeholder: "choisir des tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"


