daktary:
  home: /multibao/contributions/pages
  meta:
    title: 'MultiBào : Une multi-boite à outils'
    description: 'multiBàO permet aux animateurs de réseaux publiant des ressources participatives sur leurs sites web de pleinement les mutualiser.'

  ghRepos:
    - label: Menu
      account: multibao
      repo: contributions
      folder: pages
      
    - label: Public
      account: multibao
      repo: contributions
      folder: contributions

    - label: Moustics
      account: multibao
      repo: contributions/contributions
      folder: moustic

    - label: Réseau transition
      account: reseautransitionwb
      repo: reseau_transition
      folder: contributions
  
    - label: Démocratie Ouverte
      account: alecoz
      repo: democratie_ouverte
      folder: contributions

    - label: Cpcoop
      account: multibao
      repo: contributions/contributions
      folder: cpcoop

    - label: Fnh
      account: multibao
      repo: contributions/contributions
      folder: fnh

    - label: Chiendent
      account: multibao
      repo: contributions/contributions
      folder: collectif_chiendent
  
    - label: Les traducteurs agiles
      account: les-traducteurs-agiles
      repo: les-traducteurs-agiles.github.io
      folder: _posts

    - label: Holacraty
      account: holacracyone
      repo: Holacracy-Constitution
      folder: 

    - label: D SIDD
      account: multibao
      repo: contributions/contributions
      folder: d_sidd

    - label: J.e.u.
      account: multibao
      repo: contributions/contributions
      folder: jeu

  dkCss: assets/css/multibao.css
  dkImgPath: assets/img
  dk404: https://raw.githubusercontent.com/daktary/contribs/master/assets/img/error404.png

prose:
  rooturl: 'contributions'
  media: 'media'
  metadata:
    contributions:
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "Contribution multibao"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"
